/**
 * Каталог источников знаний: различаем машинно-сгенерированные данные и
 * написанные вручную.
 *
 * Зачем: файл `src/data/schemas.ts` был помечен как `verified`, хотя это
 * рукописная документация — именно в ней долго жила неверная конвенция
 * `class ... extends cmsInstaller`. Уровень достоверности должен быть
 * заслуженным, а не заявленным.
 */

export type KnowledgeConfidence = 'verified' | 'inferred' | 'legacy';
export type KnowledgeProvenance = 'generated' | 'curated';

export interface CatalogSource {
  id: string;
  runtime_file: string;
  domain: string;
  confidence: KnowledgeConfidence;
  provenance: KnowledgeProvenance;
  verified_at: string;
}

/** Признаки файла, который создан парсером, а не написан вручную. */
const GENERATED_MARKERS = [
  /AUTO-GENERATED/i,
  /Auto-generated from/i,
  /Generated from official/i,
  /Generated by scripts\//i,
];

export const GENERATED_HEADER_LINES = 5;

export function looksGenerated(content: string): boolean {
  const head = content.split('\n').slice(0, GENERATED_HEADER_LINES).join('\n');
  return GENERATED_MARKERS.some(marker => marker.test(head));
}

/**
 * Проверяет согласованность каталога.
 * Возвращает список проблем; пустой список — каталог корректен.
 */
export function validateKnowledgeSources(
  sources: CatalogSource[],
  read: (runtimeFile: string) => string | null
): string[] {
  const problems: string[] = [];
  const seen = new Set<string>();

  for (const source of sources) {
    if (seen.has(source.id)) problems.push(`дублирующийся id источника: ${source.id}`);
    seen.add(source.id);

    if (!/^\d{4}-\d{2}-\d{2}$/.test(source.verified_at)) {
      problems.push(`${source.id}: verified_at должен быть в формате YYYY-MM-DD`);
    }

    const content = read(source.runtime_file);
    if (content === null) {
      problems.push(`${source.id}: файл не найден — ${source.runtime_file}`);
      continue;
    }

    const generated = looksGenerated(content);

    // `verified` — только для данных, полученных из закреплённого исходника.
    if (source.confidence === 'verified') {
      if (source.provenance !== 'generated') {
        problems.push(
          `${source.id}: confidence=verified требует provenance=generated (${source.runtime_file})`
        );
      }
      if (!generated) {
        problems.push(
          `${source.id}: файл ${source.runtime_file} не помечен как сгенерированный, но объявлен verified`
        );
      }
    }

    if (source.confidence !== 'verified' && source.provenance === 'generated') {
      problems.push(
        `${source.id}: provenance=generated, но confidence=${source.confidence} — укажите verified`
      );
    }

    if (source.confidence === 'inferred' && generated) {
      problems.push(
        `${source.id}: файл ${source.runtime_file} сгенерирован, поэтому его можно объявить verified`
      );
    }
  }

  return problems;
}

/** Сводка по каталогу для отчёта в get_server_capabilities. */
export function summarizeKnowledgeSources(sources: CatalogSource[]): {
  total: number;
  verified: number;
  inferred: number;
  legacy: number;
  inferred_domains: string[];
} {
  const by = (confidence: KnowledgeConfidence): CatalogSource[] =>
    sources.filter(source => source.confidence === confidence);

  return {
    total: sources.length,
    verified: by('verified').length,
    inferred: by('inferred').length,
    legacy: by('legacy').length,
    inferred_domains: [...new Set(by('inferred').map(source => source.domain))].sort(),
  };
}
