import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parse } from 'yaml';
import { z } from 'zod';

const schema = z.object({
  schema_version: z.literal(1),
  instantcms: z.object({ tested_version: z.string(), minimum_version: z.string() }),
  upstream: z.object({
    repository: z.string().url(),
    state_file: z.string().min(1),
  }),
  sources: z
    .array(
      z.object({
        id: z.string().regex(/^[a-z0-9-]+$/),
        runtime_file: z.string().min(1),
        domain: z.enum([
          'hooks',
          'components',
          'schemas',
          'database',
          'events',
          'controllers',
          'widgets',
          'traits',
          'fields',
          'core',
        ]),
        confidence: z.enum(['verified', 'inferred', 'legacy']),
        verified_at: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
      })
    )
    .min(1),
});

async function main(): Promise<void> {
  const projectRoot = process.cwd();
  const source = schema.parse(
    parse(await readFile(resolve(projectRoot, 'knowledge/catalog.yaml'), 'utf8'))
  );
  const ids = new Set<string>();
  const upstream = JSON.parse(
    await readFile(resolve(projectRoot, source.upstream.state_file), 'utf8')
  ) as { repository?: string; commit?: string };
  if (upstream.repository !== source.upstream.repository || !upstream.commit) {
    throw new Error('Invalid InstantCMS upstream state');
  }
  for (const item of source.sources) {
    if (ids.has(item.id)) throw new Error(`Duplicate knowledge source id: ${item.id}`);
    ids.add(item.id);
    await readFile(resolve(projectRoot, item.runtime_file));
  }

  const generated = `// Generated by scripts/build-knowledge.ts. Do not edit.\nexport const knowledgeCatalog = ${JSON.stringify(source, null, 2)} as const;\n`;
  await writeFile(resolve(projectRoot, 'src/generated/knowledge-meta.ts'), generated);
  console.log(`Validated ${source.sources.length} knowledge sources.`);
}

void main();
