import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { discoverHooks } from '../src/tools/parser/hooks-parser.js';
import { parseAllCoreFiles } from '../src/tools/parser/core-parser.js';

const projectRoot = process.cwd();
const checkout = resolve(projectRoot, '.cache/icms2');
const versions = [
  { version: '2.16', ref: '2.16.3' },
  { version: '2.17', ref: '2.17.3' },
  { version: '2.18.1', ref: '2.18.1' },
  { version: '2.18.2', ref: '2.18.2' },
] as const;

function git(...args: string[]): string {
  return execFileSync('git', ['-C', checkout, ...args], { encoding: 'utf8' }).trim();
}

function snapshot(version: string, ref: string) {
  const root = mkdtempSync(join(tmpdir(), 'icms-version-api-'));
  try {
    const archive = execFileSync('git', ['-C', checkout, 'archive', ref, 'system'], {
      maxBuffer: 100 * 1024 * 1024,
    });
    const extracted = spawnSync('tar', ['-xf', '-', '-C', root], { input: archive });
    if (extracted.status !== 0) throw new Error(`Cannot extract InstantCMS ${ref}`);
    const hooks = Object.fromEntries(discoverHooks(root).map(hook => [hook.name, hook.files]));
    const methods = Object.fromEntries(
      parseAllCoreFiles(root).map(component => [
        component.name,
        {
          file: `system/core/${component.file}.php`,
          names: component.methods
            .filter(method => method.visibility === 'public')
            .map(method => method.name)
            .sort(),
        },
      ])
    );
    return { version, ref, commit: git('rev-parse', `${ref}^{commit}`), hooks, methods };
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

const evidence = {
  schema_version: 1,
  repository: 'https://github.com/instantsoft/icms2.git',
  snapshots: versions.map(({ version, ref }) => snapshot(version, ref)),
};
const json = `${JSON.stringify(evidence, null, 2)}\n`;
const generated =
  '// Generated by scripts/build-version-api.ts from official InstantCMS tags. Do not edit.\n' +
  'export interface VersionApiEvidence {\n' +
  '  schema_version: number;\n  repository: string;\n' +
  '  snapshots: Array<{\n    version: string; ref: string; commit: string;\n' +
  '    hooks: Record<string, string[]>;\n' +
  '    methods: Record<string, { file: string; names: string[] }>;\n' +
  '  }>;\n}\n' +
  `export const versionApiEvidence: VersionApiEvidence = ${JSON.stringify(evidence, null, 2)};\n`;
const outputs = [
  [resolve(projectRoot, 'knowledge/version-api.json'), json],
  [resolve(projectRoot, 'src/generated/version-api.ts'), generated],
] as const;

for (const [path, content] of outputs) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) {
      throw new Error(`Version API evidence differs: ${path}`);
    }
  } else {
    writeFileSync(path, content);
  }
}
console.log(`Version API evidence: ${versions.map(item => item.ref).join(', ')}`);
